@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor STORAGE_COLOR
skinparam classBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {

package "UserPrefs Storage" #F4F6F6{
Class "<<interface>>\nUserPrefsStorage" as UserPrefsStorage
Class JsonUserPrefsStorage
}

Class "<<interface>>\nStorage" as Storage
Class StorageManager

package "HospitalContacts Storage" #F4F6F6{
Class "<<interface>>\nHospitalContactsStorage" as HospitalContactsStorage
Class JsonHospitalContactsStorage
Class JsonSerializableHospitalContacts
Class JsonAdaptedPerson
Class JsonAdaptedTag
}

}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Storage

StorageManager .up.|> Storage
StorageManager -up-> "1" UserPrefsStorage
StorageManager -up-> "1" HospitalContactsStorage

Storage -left-|> UserPrefsStorage
Storage -right-|> HospitalContactsStorage

JsonUserPrefsStorage .up.|> UserPrefsStorage
JsonHospitalContactsStorage .up.|> HospitalContactsStorage
JsonHospitalContactsStorage ..> JsonSerializableHospitalContacts
JsonSerializableHospitalContacts --> "*" JsonAdaptedPerson
JsonAdaptedPerson --> "*" JsonAdaptedTag

@enduml
