@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedHospitalContactsXpm" as VersionedHospitalContactsXpm MODEL_COLOR
end box

[-> Model : undoHospitalContactsXpm()
activate Model

Model -> VersionedHospitalContactsXpm : undo()
activate VersionedHospitalContactsXpm

VersionedHospitalContactsXpm -> VersionedHospitalContactsXpm :resetData(ReadOnlyHospitalContactsXpm)
VersionedHospitalContactsXpm --> Model :
deactivate VersionedHospitalContactsXpm

[<-- Model
deactivate Model

@enduml
