@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedHospitalContacts" as VersionedHospitalContacts MODEL_COLOR
end box

[-> Model : undoHospitalContacts()
activate Model

Model -> VersionedHospitalContacts : undo()
activate VersionedHospitalContacts

VersionedHospitalContacts -> VersionedHospitalContacts :resetData(ReadOnlyHospitalContacts)
VersionedHospitalContacts --> Model :
deactivate VersionedHospitalContacts

[<-- Model
deactivate Model

@enduml
