@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":HospitalContactsParser" as HospitalContactsParser LOGIC_COLOR
participant "u:UndoCommand" as UndoCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box
[-> LogicManager : execute(undo)
activate LogicManager

LogicManager -> HospitalContactsParser : parseCommand(undo)
activate HospitalContactsParser

create UndoCommand
HospitalContactsParser -> UndoCommand
activate UndoCommand

UndoCommand --> HospitalContactsParser
deactivate UndoCommand

HospitalContactsParser --> LogicManager : u
deactivate HospitalContactsParser

LogicManager -> UndoCommand : execute()
activate UndoCommand

UndoCommand -> Model : undoHospitalContacts()
activate Model

Model --> UndoCommand
deactivate Model

UndoCommand --> LogicManager : result
deactivate UndoCommand
UndoCommand -[hidden]-> LogicManager : result
destroy UndoCommand

[<--LogicManager
deactivate LogicManager
@enduml
